CREATE TABLE Modules(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL);

CREATE TABLE Terms(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	answer TEXT NOT NULL,
	question TEXT NOT NULL,
	module INTEGER NOT NULL,
	FOREIGN KEY(module) REFERENCES Modules(id));